project:
  type: website

website:
  title: "cole_press"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog/index.qmd
        text: Blog

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

