project:
  type: website
  title: "cole.press"
  resources:
    - fonts/

website:
  title: "cole.press"
  description: "A personal website by Cole, with thoughts on tech, AI, psychology, and politics."
  site-url: "https://cole.press"
  repo-url: "https://github.com/colerehbein/cole_press"
  search: true
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog/index.qmd
        text: Blog
    right:
      - icon: fab fa-github
        href: https://github.com/colerehbein
      - icon: fab fa-twitter
        href: https://twitter.com/colerehbein

format:
  html:
    theme:
      light: monospatial-light.scss
      dark: monospatial-dark.scss
    toc: true
    include-in-header: _includes/preload-fonts.html
    code-fold: true
    code-summary: "Show code"
    code-tools: true
    execute:
      cache: true
      echo: true
      warning: false
    highlight-style:
      light: github
      dark: monokai
    html-math-method: katex
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 250px

params:
  author: "Cole Rehbein"
  date_format: "MMM D, YYYY"

editor: visual

