name: Build & Deploy to Netlify

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Install R ---
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      # If you need R packages, restore them here (optional)
      # - name: Restore R env (renv example)
      #   run: |
      #     if [ -f renv.lock ]; then
      #       Rscript -e 'install.packages("renv"); renv::restore()'
      #     fi

      # --- Install Quarto ---
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: false    # flip to true if you start making PDFs

      # --- Render site ---
      - name: Render
        run: quarto render

      # --- Deploy to Netlify ---
      - name: Deploy
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: _site
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID:   ${{ secrets.NETLIFY_SITE_ID }}
