name: Build & Deploy to Netlify

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install R; pin version to match your other workflow
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.5.1"

      # Install R dependencies from DESCRIPTION (incl. knitr & rmarkdown)
      - name: Install R deps
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # extra-packages ensures pak is available for fast installs
          extra-packages: any::pak

      # Install Quarto
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: false

      # Render the site
      - name: Render site
        run: quarto render

      # Deploy to Netlify
      - name: Deploy
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: _site
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
